[build]
  functions = "netlify/functions"

[functions."election-results"]
  external_node_modules = [
    "chromium-bidi",
    "../../../package.json"
  ]

[[plugins]]
  package = "netlify-plugin-playwright-cache"